### ISSUE TITLE
no-default-params doesn' work

### ISSUE THREAD

**Issue by AlexZeitler** [NatureFeng/eslint-plugin-no-es2015#4]
First things first: thanks for this plugin which perfectly fits my needs in a particular project :+1: 

I noticed that the `no-default-params` rule doesn't catch this function signature which uses a default param:

```
vm.loadMore = function(days = 7) {
}
```

**Comment by NatureFeng** [comment]
you can check your .eslintrc file

if you dont have this rule "no-es2015/no-default-params", it will not working.
